### ISSUE TITLE
Progress Checklist

### ISSUE THREAD

**Issue by WaterGenie35** [Thirdwater/django-quick-start#1]
### Philosophy

- [ ] [Design Philosophies](https://docs.djangoproject.com/en/3.1/misc/design-philosophies/)

### First Steps

Get through all of these first.

  - [x] From Scratch (see `mod_wsgi` on Apache and specific db backends when appropriate)
    - [x] Overview
  - [x] Tutorial
    - [x] Part 1: Requests and Responses
    - [x] Part 2: Models and the Admin Site
    - [x] Part 3: Views and Templates
    - [x] Part 4: Forms and Generic Views
    - [x] Part 5: Testing
    - [x] Part 6: Static Files
    - [x] Part 7: Customizing the Admin Site
  - [x] Advanced Tutorials
    - [x] How to Write Reusable Apps

### Topics

Visit any of these whenever appropriate to get a higher-level overview of the concepts involved.
Check these alongside the categories on the doc's main page to get a better picture since there will be a lot of overlaps.

- [ ] Models and Databases
- [ ] Handling HTTP Requests
- [ ] Working with Forms
- [ ] Templates
- [ ] Class-based Views
- [ ] Migrations
- [ ] Managing Files
- [ ] Testing
- [ ] User Authentication
- [ ] Cache Framework
- [ ] Conditional View Processing
- [ ] Cryptographic Signing
- [ ] Sending Email
- [ ] i18n and l12n
- [ ] Logging
- [ ] Pagination
- [ ] Security
- [ ] Performance and Optimization
- [ ] Serializing Django Objects
- [ ] Django Settings
- [ ] Signals
- [ ] System Check Framework
- [ ] External Packages
- [ ] Asynchronous Support

### Categories
- [ ] The Model Layer
  - [ ] Models
  - [ ] QuerySets
  - [ ] Model Instances
  - [ ] Migrations
  - [ ] Advanced
  - [ ] Other
- [ ] The View Layer
  - [ ] Basics
  - [ ] Reference
  - [ ] File Uploads
  - [ ] Class-based Views
  - [ ] Advanced
  - [ ] Middleware
- [ ] The Template Layer
  - [ ] Basics
  - [ ] For Designers
  - [ ] For Programmers
- [ ] Forms
  - [ ] Basics
  - [ ] Advanced
- [ ] The Development Process
  - [ ] Settings
  - [ ] Applications
  - [ ] Exceptions
  - [ ] `django-admin` and `manage.py`
  - [ ] Testing
  - [ ] Deployment
- [ ] The Admin
- [ ] Security
- [ ] i18n and l12n
- [ ] Performance and Optimization
- [ ] Geographic Framework
- [ ] Common Web Application Tools
- [ ] Other Core Functionalities

### References and How-Tos

Go to the corresponding topics first, and use these sections when developing.

**Comment by WaterGenie35** [comment]
## Django by Example (YouTube playlist by Noah Rubin)

[(link)](https://www.youtube.com/playlist?list=PLAF3anQEEkzS-mjdX7s-D63bjLWRdhuFM)

- [x] Django Structure
- [x] Project Structure
- [x] Basic View and URL Mapping
- [x] Basic Templates
- [ ] Models
- [ ] Shell
- [ ] Admin Site
- [ ] Using Models in Templates
- [ ] For Loops in Templates
- [ ] Dynamic Views/URLs
- [ ] If Statements in Templates / Handling DoesNotExist
- [ ] Template Inheritance
- [ ] Foreign Keys
- [ ] Serving Static Files During Development
- [ ] Images in Models
- [ ] Serving Media Files During Development
